version: "3.1"
services:
  db:
    image: mariadb
    container_name: playground_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: playground
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - playground
  nginx:
    image: nginx:latest
    container_name: playground_nginx
    working_dir: /www
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./www/:/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - playground
  php:
    build: docker/php
    container_name: playground_php
    working_dir: /www
    volumes:
      - ./www/:/www
    networks:
      - playground
  mailhog:
    image: mailhog/mailhog:latest
    container_name: playground_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - playground
networks:
  playground:
    driver: bridge