version: "3.1"
services:
  mysql:
    image: mysql:8.0
    container_name: playground-db
    working_dir: /app
    volumes:
      - ./app/:/app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=playground
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
    networks:
      - playground


  nginx:
    image: nginx:latest
    container_name: playground-nginx
    working_dir: /app
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./app/:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - playground

  php:
    build: docker/php
    container_name: playground-php
    working_dir: /app
    volumes:
      - ./app/:/app
    networks:
      - playground

  mailhog:
    image: mailhog/mailhog:latest
    container_name: playground-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - playground

networks:
  playground:
    driver: bridge